### ISSUE TITLE
Get 'unexpected token' when pattern is not inside of string.

### ISSUE THREAD

**Issue by marocchino** [WhitePayments/match_json#1]
```
  1) include_json with custom pattern uses patten to check value
     Failure/Error: expect(%Q({"one": 123456})).to include_json(%Q({"one": {id}}))
     JSON::ParserError:
       757: unexpected token at '{"one": {id}}'
     # ./lib/match_json/matchers/include_json.rb:14:in `initialize'
     # ./lib/match_json/matchers.rb:6:in `new'
     # ./lib/match_json/matchers.rb:6:in `include_json'
     # ./spec/match_json/matchers_spec.rb:83:in `block (3 levels) in <top (required)>'
```

**Comment by alovak** [comment]
@marocchino thanks for reporting.

The reason why you see this is that on the right side you have invalid json:

```json
{"one": {id}}
```
but I see why you have it so. Unfortunately I don't know how to solve it :( I will think about it.
Do you have any ideas?

**Comment by marocchino** [comment]
Sorry but, I don't have simple answer, either. >_<
Maybe, we could change the expected json. It dose not need to be a json in this case.
